<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HolzShots.Input.Keyboard</RootNamespace>

    <TargetFramework>net10.0-windows</TargetFramework>
    <Version>0.0.0</Version> <!-- Set via -p:Version= in CI -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Niklas Mollenhauer</Authors>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>

    <Description>Global hotkey library for Windows Forms applications, used by HolzShots.</Description>
    <PackageTags>hotkey;global-hotkey;keyboard;winforms;windows</PackageTags>
    <PackageProjectUrl>https://holzshots.net</PackageProjectUrl>

    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>

    <PackageReadmeFile>README.md</PackageReadmeFile>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- CS1591: Missing XML comment for publicly visible type or member -->
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <!-- SourceLink Support -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <RepositoryUrl>https://github.com/HolzShots/HolzShots.Input.Keyboard</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All"/>
  </ItemGroup>

</Project>
